Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\anaconda3\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Un bucle para garantizar que el mes introducido es correcto

mes = int(input("Introduzca el mes del aÃ±o (entre 1 y 12): "))

while mes > 12 or mes < 1:
    print("Mes introducido incorrecto. IntÃ©ntelo de nuevo")
    mes = int(input("Introduzca el mes del aÃ±o (entre 1 y 12):"))

print("El mes {} es vÃ¡lido".format(mes))
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mStdinNotImplementedError[0m                  Traceback (most recent call last)
[1;32m<ipython-input-1-22ae856f02ca>[0m in [0;36m<module>[1;34m[0m
[0;32m      1[0m [1;31m# Un bucle para garantizar que el mes introducido es correcto[0m[1;33m[0m[1;33m[0m[1;33m[0m[0m
[0;32m      2[0m [1;33m[0m[0m
[1;32m----> 3[1;33m [0mmes[0m [1;33m=[0m [0mint[0m[1;33m([0m[0minput[0m[1;33m([0m[1;34m"Introduzca el mes del aÃ±o (entre 1 y 12): "[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      4[0m [1;33m[0m[0m
[0;32m      5[0m [1;32mwhile[0m [0mmes[0m [1;33m>[0m [1;36m12[0m [1;32mor[0m [0mmes[0m [1;33m<[0m [1;36m1[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m

[1;32mC:\Anaconda3\lib\site-packages\ipykernel\kernelbase.py[0m in [0;36mraw_input[1;34m(self, prompt)[0m
[0;32m    856[0m         [1;32mif[0m [1;32mnot[0m [0mself[0m[1;33m.[0m[0m_allow_stdin[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[0;32m    857[0m             raise StdinNotImplementedError(
[1;32m--> 858[1;33m                 [1;34m"raw_input was called, but this frontend does not support input requests."[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m    859[0m             )
[0;32m    860[0m         return self._input_request(str(prompt),

[1;31mStdinNotImplementedError[0m: raw_input was called, but this frontend does not support input requests.
StdinNotImplementedError: raw_input was called, but this frontend does not support input requests.

