Traceback (most recent call last):
  File "c:\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "c:\anaconda3\lib\site-packages\nbclient\util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "c:\anaconda3\lib\site-packages\nbclient\util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "c:\anaconda3\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 541, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "c:\anaconda3\lib\site-packages\nbclient\client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
%reset -f
# Leyendo del fichero "valores_en_fila.txt" l√≠nea a l√≠nea
fich_ent = open('valores_en_fila.txt', 'r')  # Apertura

lista_enteros = []
for linea in fich_ent:
    lista_enteros.append(int(linea))

print(lista_enteros)
    
fich_ent.close()  # Cierre
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mValueError[0m                                Traceback (most recent call last)
[1;32m<ipython-input-3-f63e6c08995e>[0m in [0;36m<module>[1;34m[0m
[0;32m      5[0m [0mlista_enteros[0m [1;33m=[0m [1;33m[[0m[1;33m][0m[1;33m[0m[1;33m[0m[0m
[0;32m      6[0m [1;32mfor[0m [0mlinea[0m [1;32min[0m [0mfich_ent[0m[1;33m:[0m[1;33m[0m[1;33m[0m[0m
[1;32m----> 7[1;33m     [0mlista_enteros[0m[1;33m.[0m[0mappend[0m[1;33m([0m[0mint[0m[1;33m([0m[0mlinea[0m[1;33m)[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m
[0m[0;32m      8[0m [1;33m[0m[0m
[0;32m      9[0m [0mprint[0m[1;33m([0m[0mlista_enteros[0m[1;33m)[0m[1;33m[0m[1;33m[0m[0m

[1;31mValueError[0m: invalid literal for int() with base 10: '1 2 3 4 5 6 7 8 9 10\n'
ValueError: invalid literal for int() with base 10: '1 2 3 4 5 6 7 8 9 10\n'

